version: '3.8'
services:
  web:
    build:
      context: ./
    # volumes:
    #   - .:/src
    #   - ./node_modules
    command: npm run serve
    ports:
      - "80:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*